### ISSUE TITLE
Get server messages in cs go

### ISSUE THREAD

**Issue by Zik42** [SnoutBug/csgotts#1]
Hi, I explored your python package. I have question, why dont I have server messages in csgo console? Can I get chat somehow? Pls, will be glad for ur advice.

**Comment by SnoutBug** [comment]
The code is no longer available in Python it has been rewritten in C#. 
Can you please clarify your issue?

**Comment by Zik42** [comment]
Its not as an issue, I just ask for your advice. I write some script in python and I cant get chat messages from server in any way. Dont know where I need to dig in...

**Comment by SnoutBug** [comment]
If you enable **-condebug** in your csgo launch options, Counterstrike will create a **console.log** file in the folder **Counter-Strike Global Offensive\csgo**
That will contain the chat messages

**Comment by Zik42** [comment]
@SnoutBug  Yes I did it. The problem is, I have no messages from server with some info. I only show messages from  players and other logs. I used player_nevershow_communityservermessage, but no effect. Dont know architecture of game, dont know where to dig. Do you have any ideas?

**Comment by SnoutBug** [comment]
No, I'm afraid I can't help you in this matter.
